title: 'Mia Tran' 
author: 
        name: 'Mia Tran'
        url: "https://mytran2111.github.io/" 
        email: 'my.d.tran@mail.mcgill.ca'
        github: 'https://github.com/mytran2111'
        linkedin: 'https://www.linkedin.com/in/my-duc-tran-1909/'
        resume: 'https://mytran2111.github.io/MyTran_Spring2023.pdf'
description: >- 
        BSc. Statistics and Computer Science @ McGill 

baseurl: "" 

# github:
#         repo: https://github.com/mytran2111

markdown: kramdown
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-remote-theme
