title: 'My Duc Tran' 
author: 
        name: 'My Duc Tran'
        url: "https://mytran2111.github.io/" 
        email: 'my.d.tran@mail.mcgill.ca'
        github: 'https://github.com/mytran2111'
        linkedin: 'https://www.linkedin.com/in/my-duc-tran-2341a8191/'
description: >- 
        BSc. Statistics and Computer Science @ McGill  
baseurl: "" 

github:
        repo: https://github.com/mytran2111

markdown: kramdown
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-remote-theme
